version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    restart: always

  backend:
    build:
      context: ./backend
    restart: always
    environment:
      - PORT=5000

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always
