version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    restart: always

  backend:
    build:
      context: ./backend
    restart: always
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://database:27017/trackflow
      - JWT_SECRET=super_secret_devops_key_123
      - JWT_EXPIRE=30d
    depends_on:
      - database

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always

  database:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
